// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztqyelnzuvmkgwettqls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cXllbG56dXZta2d3ZXR0cWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDc0MjAsImV4cCI6MjA2ODkyMzQyMH0.MQU2zhAcoBOAz4-TtoGDcyz7V04S3_D1d9DOgq66Rqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});